export const KAZAKHSTAN_REGIONS = [
    { id: "astana", name: "г. Астана" },
    { id: "almaty", name: "г. Алматы" },
    { id: "shymkent", name: "г. Шымкент" },
    { id: "abai", name: "Абайская область" },
    { id: "akmola", name: "Акмолинская область" },
    { id: "aktobe", name: "Актюбинская область" },
    { id: "almaty_reg", name: "Алматинская область" },
    { id: "atyrau", name: "Атырауская область" },
    { id: "east_kaz", name: "Восточно-Казахстанская область" },
    { id: "jambyl", name: "Жамбылская область" },
    { id: "zhetysu", name: "Жетысуская область" },
    { id: "west_kaz", name: "Западно-Казахстанская область" },
    { id: "karaganda", name: "Карагандинская область" },
    { id: "kostanay", name: "Костанайская область" },
    { id: "kyzylorda", name: "Кызылординская область" },
    { id: "mangystau", name: "Мангистауская область" },
    { id: "pavlodar", name: "Павлодарская область" },
    { id: "north_kaz", name: "Северо-Казахстанская область" },
    { id: "turkistan", name: "Туркестанская область" },
    { id: "ulytau", name: "Улытауская область" },
] as const;
